// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerAPI.Db;

namespace SneakerAPI.Db.Migrations
{
    [DbContext(typeof(SneakerContext))]
    [Migration("20210616191326_CreateSneakersTables")]
    partial class CreateSneakersTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SneakerAPI.Models.Sneaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorWay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sneakers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8448b56-dff2-44ec-80e7-851096dbfec1"),
                            Brand = "Nike",
                            ColorWay = "White",
                            Description = "Perhaps the most iconic Nike sneaker of all-time.",
                            Name = "Air Force 1",
                            ReleaseYear = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af521968-3a09-4248-a042-98879053ef8e"),
                            Brand = "Adidas ",
                            ColorWay = "White",
                            Description = "The adidas Stan Smith tennis shoe design debuted in 1963 as the adidas Robert Haillet.",
                            Name = "Stan Smith",
                            ReleaseYear = new DateTime(1963, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
